serverAddr = "192.168.11.48"
serverPort = 7000
auth.token = "game_frp"

[[proxies]]
name = "test-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000


[[proxies]]
name = "web"
type = "http"	
localIP = "127.0.0.1"
localPort = 3309						
customDomains = ["192.168.11.48"]
