serverAddr = "192.168.11.48"
serverPort = 7000
auth.token = "game_frp"

[[proxies]]
name = "cloud"
type = "tcp"
localIP = "127.0.0.1"
localPort = 7010 #自己的服务端口
remotePort = 7010 #对外的访问端口: 192.168.11.48:7010

[[proxies]]
name = "zero"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3309 #自己的服务端口
remotePort = 7020 #对外的访问端口

[[proxies]]
name = "boros"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3309 #自己的服务端口
remotePort = 7030 #对外的访问端口

[[proxies]]
name = "ant"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3309 #自己的服务端口
remotePort = 7040 #对外的访问端口


# [[proxies]]
# name = "web"
# type = "http"	
# localIP = "127.0.0.1"
# localPort = 3309						
# customDomains = ["192.168.11.48"]

